### ISSUE TITLE
No module named MDmisc

### ISSUE THREAD

**Issue by ciurescum** [mdedonno1337/NIST#2]
Hello Marco,

I was trying to import the NIST Module, but I got an error regarding the MDmisc module: "ImportError:No module named MDmisc". Is there any way you can commit the MDmisc module to this project?

**Comment by mdedonno1337** [comment]
Hi,
Nope, the two projects are different, hence not possible to merge the history.

The link is here:
https://github.com/mdedonno1337/MDmisc

By the way, all dependencies need to be installed manually. The best way is to clone all dependencies in a folder, and link the folders with a .pth file.
All libs are available in my depo.

**Comment by mdedonno1337** [comment]
Hi,

Here is the full installation process : https://github.com/mdedonno1337/NISTfull

Have fun.
