### ISSUE TITLE
Unable to modify field 9.004 from S to U

### ISSUE THREAD

**Issue by Picard2200** [mdedonno1337/NIST#3]
Hi,

First I would like to say that I love your library: very easy to use and I have been able to generate NIST files with records 10 and 14 with no issue and very easily (I insist on that point). I love it so much that I am thinking about porting it to Python 3.

I try to generate a latent NIST file with field 9.004 set to U instead the hard coded S and do not succeed to do it.

I started from your example doctester.py and just added the line mark.set_field("9.004", 'U') .
I still have S when I print the mark record.

Below is my code:

```
# -*- coding: UTF-8 -*-

import NIST.core.functions
import NIST.traditional.__init__

import NIST.fingerprint.__init__
import NIST.fingerprint.functions

import NIST.plugins.MDD.__init__
from NIST.fingerprint.functions import AnnotationList
from MDmisc.string import join, join_r
from NIST.core.config import RS, US

l_mark = NIST.fingerprint.__init__.NISTf()
l_mark.add_Type01()
l_mark.add_Type02()

l_idc = 1
l_mark.add_Type09(l_idc)
#
lst = [
    [1, 7.85, 7.05, 290, 0, 'A'],
    [2, 13.80, 15.30, 155, 0, 'A'],
    [3, 11.46, 22.32, 224, 0, 'B'],
    [4, 22.61, 25.17, 194, 0, 'A'],
    [5, 6.97, 8.48, 153, 0, 'B'],
    [6, 12.58, 19.88, 346, 0, 'A'],
    [7, 19.69, 19.80, 111, 0, 'C'],
    [8, 12.31, 3.87, 147, 0, 'A'],
    [9, 13.88, 14.29, 330, 0, 'D'],
    [10, 15.47, 22.49, 271, 0, 'D']
]

minutiae = AnnotationList()
minutiae.from_list(lst, format="ixytqd", type='Minutia')

l_mark.set_minutiae(minutiae, l_idc)
l_mark.set_field("9.004", 'U')
#

lst = [
    [12.5, 18.7],
    [10.0, 12.7]
]

cores = AnnotationList()
cores.from_list(lst, "xy", "Core")
# l_mark.set_cores([[12.5, 18.7]], 1)

l_mark.add_Type13((500, 500), 500, l_idc)
print(l_mark)
```

**Comment by Picard2200** [comment]
After investigation using Pycharm debugger, the set_field is properly performed but if I let set_minutiae (even before the set_field(9.004), set_cores and add_Type13, field 9.004 is forced back to S :-(

**Comment by mdedonno1337** [comment]
Hi Picard,
Thanks for this issue.
I have already worked a on a python3 version, but the work is difficult to do because this lib is integrated on a LOOOT of projects... I have to start from scratch (a lot is already done).

Regarding the field 9.004, the NIST standard indicates that:

> This mandatory field is retained only for backward compatibility. It was a mandatory field in previous versions of the standard. This field shall always have a value “U”, unless including legacy fields 9.005 through 9.012 (described in ANSI/NIST-ITL 1-2007 and ANSI/NIST-ITL 2-2008), when this field shall contain “S”.

Beeing non-english speeker, I understaand that, if the some legacy fields are present (005 - 012), the field shall be 'S'.

In the current version of this lib, I use the field 9.012 by default, but the M1 format is also available.

Let me know how you understand the NIST standard.

**Comment by Picard2200** [comment]
Hi Marco,

Thank you for your quick answer!

On the adaptation to Python 3, maybe we can work together!

Regarding the field 9.004, it is said that you have to put ‘U’ by default.
But if fields 9.005 to 9.012 are specified then field 9.004 shall have the value ’S’

In my case, I do not have the fields 9.005 to 9.012 so it should be a ‘U’ for me.

The fix for me would be to put ’S’ only if fields 9.005 to 9.012 are provided, ‘U’ otherwise

If at least one of the fields 9.005 to 9.012 is specified, you need to have all the fields 9.005 to 9.012.
And ’S’ shall be put in 9.004.

If you tell me where I can find the hard coded part, I can fix it if you want.

You have done a great job, really amazing!

If you need, I am french but I speak spanish too so if it is not clear enough, we could exchange emails in spanish or french (I am starting to study italian)

**Comment by mdedonno1337** [comment]
From Switzerland on my side, and speaking french.

Regarding your example, the `set_minutiae` function set the field `9.012` by default. 
If you add a `print` statement just after the `9.004 set_field`, you will have this output:

```Informations about the NIST object:
    Obj ID:  eaffda1e09599c87ae9f404b8309cc5b
    Records: Type-01, Type-02, Type-09
    Class:   NISTf

NIST Type-01
    01.001 LEN: 00000140
    01.002 VER: 0300
    01.003 CNT: 1<US>2<RS>2<US>0<RS>9<US>1
    01.004 TOT: USA
    01.005 DAT: 20201217
    01.006 PRY: 1
    01.007 DAI: FILE
    01.008 ORI: UNIL
    01.009 TCN: 1608236984
    01.011 NSR: 00.00
    01.012 NTR: 00.00
NIST Type-02 (IDC 0)
    02.001 LEN: 00000038
    02.002 IDC: 0
    02.004    : 20201217
NIST Type-09 (IDC 1)
    09.001 LEN: 00000251
    09.002 IDC: 1
    09.003 IMP: 4
    09.004 FMT: S
    09.007    : U
    09.010    : 10
    09.011    : 0
    09.012    : 1<US>07850705290<US>0<US>A<RS>2<US>13801530155<US>0<US>A<RS>3<US>11462232224<US>0<US>B<RS>4<US>22612517194<US>0<US>A<RS>5<US>06970848153<US>0<US>B<RS>6<US>12581988346<US>0<US>A<RS>7<US>19691980111<US>0<US>C<RS>8<US>12310387147<US>0<US>A<RS>9<US>13881429330<US>0<US>D<RS>10<US>15472249271<US>0<US>D 
```

A solution would be to use the `NIST_M1` class, avoiding the legacy format, right ?

I will try alter on to pass the NIST file saved by the NISTf class in the NIST validation program to double-check the compatibility against the standard and will make the patch as needed.

If you want to remove the hard-coded 'S' now waiting upon the patch here, try to check the file `fingerprint/__init__.py` file, line `163`.

**Comment by Picard2200** [comment]
Thank you Marco!

I have not looked yet at the NIST_M1 but I will do it.

Have a nice evening!
Jean-Pierre

**Comment by Picard2200** [comment]
Hi Marco,

I tried with NIST_M1 but it failed on check_minutiae: no .x field so I assume that it is expecting a named tuple.

I will have therefore a look for the other solution you suggested.

Jean-Pierre

**Comment by Picard2200** [comment]
Hi Marco,

Thanks to your advice, the fix was quite easy to find.
Since fields 9.007 and 9.011 are provided by default, the check on line 163 will force 9.004 to S, what is consistent with the standard.
The fix is to remove fields 9.007 and 9.011 from the default tags for record Type-9 (voidType.py)

**Comment by mdedonno1337** [comment]
Reading and thinking about your request, I dont understand one thing... Are you trying to create a legacy NIST file with the field 9.012, or use the 'U' value in the 9.004 field, indicating a vendor-specific format ?

If you'd like to use a vendor-specific format, the function `set_minutiae` is probably not the correct one, and you should define your own function (to convert the data-structure you have to the vendor definition, like the function `lstTo012` does for the 9.012 format.

I think I'am missing something here.

**Comment by Picard2200** [comment]
Hi Marco,

I do not use field 9.012 but fields 9.136 and  9.137 (I follow NIST 2011 update 2015)
I do not use set_minutiae but populate the minutia field using join_r.

I take advantage of this answer to say that I notice what looks like a format defect on the date field 13.005
The date is printed using format YYYY-MM-DD but it should be YYYYMMDD.
From what I see in the NIST 2011 update 2015, YYYYMMDD is for traditional encoding, YYYY-MM-DD is for XML


If you have a Python 3 version close to be working, I am interested.
I try to populate images using jpeg2000 and wsq and I do not find Python 2 libraries converting images to WSQ and JPEG2000 (lossy or lossless)

Thanks again for your concern and your very nice work (very well architectured software: a pleasure to use!

Jean-Pierre

**Comment by mdedonno1337** [comment]
I have a WIP branch here for python3.
I will check the field 13.005.
Regading the WSQ implementation, my WSQ lib does it (as least for Windows and Linux, based upon the binaries from NBIS). You have the one from IDEMIA (https://github.com/idemia/python-wsq) that imports and compile the NBIS binaries. My docker version of the NBIS does it as well (https://github.com/mdedonno1337/docker-NBIS); docker is the best way I have to share code with non Linux users, in particular the Mac users at work.

**Comment by Picard2200** [comment]
Hi Marco,

Ayant besoin de la version en Python 3, j’ai travaillé dessus et j’ai à présent une solution fonctionnelle pour mes cas d’utilisation (visage, trace, doigts dans type 14).
J’insiste sur ce dernier point car je ne peux pas dire que le code est entièrement validé.

J’ai choisi de rester autant que possible en mode string sachant que les strings de Python 3 gère l’unicode. Je garde les données binaires (image) en binaire et je ne fais la conversion en texte (hexa) que lors de l’affichage.
Si vous utilisez BeyondCompare pour voir les différences, vous verrez qu’il y en a peu.
J’ai corrigé les cas d’utilisation injustifiée de list quand l’énumérateur est utilisé dans une boucle ou un test d’appartenance.
Je les ai laissé dans un cas au moins où une liste est modifiée alors qu’on itère dessus: ce serait à revoir mais je n’ai pas encore réfléchi comment faire.
Je suis comme vous, j’ai un peu d’autres urgences :-)


Faites-moi part de vos commentaires!

Cordialement,
JEan-Pierre

**Comment by Picard2200** [comment]
Bonjour Marco,

Tout d’abord, je tiens à vous souhaiter une très bonne année 2021 pour vous et vos proches.



Côté NIST, je dois m’assurer que les NIST que je génère sont valides et j’ai donc cherché un viewer ou un validateur.
J’ai trouvé un outil (refhttps://www.nist.gov/itl/csd/biometrics-resource-center/biometric-conformance-test-software-biocts/biocts-ansinist-itl <refhttps://www.nist.gov/itl/csd/biometrics-resource-center/biometric-conformance-test-software-biocts/biocts-ansinist-itl>) qui permet de valider les fichiers NIST standard ou au format XML et il me remonte une erreur systématique sur les champs x.001: apparemment, la longueur doit être stockée sans 0 devant.
J’ai vérifié sur des NIST 14 et c’est en effet le cas.
Si je regarde les specs NIST 2011 update 2015, je n’ai pas trouvé une telle contrainte.

Cordialement,

**Comment by mdedonno1337** [comment]
Bonne année à vous aussi.
C'est correct, j'en suis conscient (c'était fait pour des questions de simplicité de programmation).
A noter que les AFIS actuels que j'ai testés ne posent aucuns problèmes quant à l'ingestion de fichiers NIST avec cette liberté au niveau des fields x.001.
